### PR TITLE
Structural models

### PR DESCRIPTION
**Pull request by gustavo-salazar**
* New table `webfront_structuralmodel` in the Django model `StructuralModel`.
* Addition of 2 modifiers for `/entry/memberDB/accession`:
  * `model:structure` returns the PDB content of models
  * `contacts` returns a JSON with the predicted contacts for the model
* New tests for the new modifiers
* Fix in the response when returning `.gz` files. Before it was returning a `.gz` that actually was already uncompressed by the browser.
* Adding documentation in the test README to explain how the gziped fixtures were created.

### CODE REVIEW

**Review by CodeGit — CHANGES_REQUESTED** [review]
It looks like a there's a stray bit of code from line 835-840 in modifiers.py. Otherwise looks good

```
def get_model_contacts(value, general_handler):
    return payload

def passing(x, y):
    pass
```

**Comment by CodeGit** [comment]
Is there an elastic index I can use for testing? At the moment:

http://localhost:8001/api/entry/pfam/pf00008/?model:structure

returns

```
GET /api/entry/pfam/pf00008/?model:structure
HTTP 404 Not Found
Allow: GET, HEAD
Content-Type: application/json
InterPro-Version: 83.0
InterPro-Version-Minor: 0
Vary: Accept

{
    "Error": 1146
}```

**Comment by gustavo-salazar** [comment]
Indeed. there is a piece of code there that should be removed. I'll commit the change in  a minute.

The change doesn't need a new elastic. The error is a mysql error saying it couldn't find the table. make sure you are pointing to this in your API config:
```
host: mysql-interpro-unifam-test.ebi.ac.uk
sid: dev
```

**Comment by gustavo-salazar** [comment]
hey @CodeGit 
this is weird, as you can see in [here](https://github.com/ProteinsWebTeam/interpro7-api/compare/dev...structurel_models) I already pushed the commit to delete those lines, but that commit for some reason is not been included here

**Pull request merged**
