### PR TITLE
Sequence(Bytes) converted to String when passed to get conservation data

### PR DESCRIPTION
**Pull request by Swaathik**

### CODE REVIEW

**Comment by gustavo-salazar** [comment]
I wonder if isn't better doing this change here instead: https://github.com/ProteinsWebTeam/interpro7-api/blob/04d615a71d53929d01444c0c24521117ba895742/webfront/models/interpro_new.py#L86

that way other places that read `sequence` can get it decoded as well.

BTW, did you manage to replicate this issue in your local machine? I haven't so I actually haven't been able to test if this fixes it.

**Comment by Swaathik** [comment]
True. I will move it there. I tested it in the local and it does work.

**Review by gustavo-salazar — APPROVED** [review]

**Comment by gustavo-salazar** [comment]
Yeah, it indeed works! what got me, is that it seems that this doesn't happen on all proteins... which I don't really understand why.
So in live this gives an error:
https://www.ebi.ac.uk/interpro/wwwapi//protein/UniProt/A0A000/?conservation=

but this doesn't:
https://www.ebi.ac.uk/interpro/wwwapi//protein/UniProt/P01050/?conservation=

In any case with your fix it seems to work in both 👍🏽

**Comment by Swaathik** [comment]
It is strange. Both should fail in live.

**Comment by gustavo-salazar** [comment]
yeah, I thought of blaming the cache but it also behaves like that locally without this fix 🤷🏽

**Pull request merged**
