### PR TITLE
Add sequence counts to entry_annotations

### PR DESCRIPTION
**Pull request by matthiasblum**
Currently, `entry_annotations` is an array of the available annotations.

For instance, for `/api/entry/pfam/PF00001/`:

```json
"entry_annotations": [
  "hmm",
  "logo",
  "alignment:uniprot",
  "alignment:full",
  "alignment:rp15",
  "alignment:rp35",
  "alignment:rp55",
  "alignment:rp75",
  "alignment:seed"
]
```

This PR changes the type of `entry_annotations` to an object where the key corresponds to the annotation type, and the value to the number of sequences in alignments (and `0` for non-alignment annotations):

```json
"entry_annotations": {
  "hmm": 0,
  "logo": 0,
  "alignment:uniprot": 266147,
  "alignment:full": 127566,
  "alignment:rp15": 24915,
  "alignment:rp35": 50446,
  "alignment:rp55": 101798,
  "alignment:rp75": 130592,
  "alignment:seed": 63
},
```

### CODE REVIEW

**Review by gustavo-salazar — APPROVED** [review]
Cool, Happy with the changes.
Question: was the `BROWSER_TEST_PATH` needed to run the tests in linux? or what created the need to include the path of chrome there?

**Comment by matthiasblum** [comment]
> Question: was the `BROWSER_TEST_PATH` needed to run the tests in linux? or what created the need to include the path of chrome there?

I forgot the mention this in the PR :confounded:.

I don't have Google Chrome on Linux but Chromium, and although it comes with ChromeDriver, the binary is `chromium.chromedriver`: Selenium cannot find `chromedriver` and the tests fail.

The change makes it possible to run tests with non-standards installs:

```sh
$ whereis chromium.chromedriver
chromium: /snap/bin/chromium /snap/bin/chromium.chromedriver
$ export BROWSER_TEST_PATH="/snap/bin/chromium.chromedriver"
$ export BROWSER_TEST="chrome"
$ python manage.py test
```

**Comment by gustavo-salazar** [comment]
> > Question: was the `BROWSER_TEST_PATH` needed to run the tests in linux? or what created the need to include the path of chrome there?
> 
> I forgot the mention this in the PR 😖.
> 
> I don't have Google Chrome on Linux but Chromium, and although it comes with ChromeDriver, the binary is `chromium.chromedriver`: Selenium cannot find `chromedriver` and the tests fail.
> 
> The change makes it possible to run tests with non-standards installs:
> 
> ```shell
> $ whereis chromium.chromedriver
> chromium: /snap/bin/chromium /snap/bin/chromium.chromedriver
> $ export BROWSER_TEST_PATH="/snap/bin/chromium.chromedriver"
> $ export BROWSER_TEST="chrome"
> $ python manage.py test
> ```

Cool, might be good to include this on a README somewhere in the test folder, not sure if we already have any documentation there.

**Comment by matthiasblum** [comment]
> Cool, might be good to include this on a README somewhere in the test folder, not sure if we already have any documentation there.

Done in 957c613.

**Pull request merged**
